support for multiple instance of chilli

diff --git a/conf/chilli.in b/conf/chilli.in
--- a/conf/chilli.in
+++ b/conf/chilli.in
@@ -22,9 +22,32 @@ killproc=killall
 }
 
 [ -f @SBINDIR@/chilli ] || exit 0
-[ -f @SYSCONFDIR@/chilli.conf ] || exit 0
 
 . @ETCCHILLI@/functions
+
+MULTI=$(ls @ETCCHILLI@/*/chilli.conf 2>/dev/null)
+[ -z "$DHCPIF" ] && [ -n "$MULTI" ] && {
+    for c in $MULTI; 
+    do
+	echo "Found configuration $c"
+	DHCPIF=$(basename $(echo $c|sed 's#/chilli.conf##'))
+	export DHCPIF
+	echo "Running DHCPIF=$DHCPIF $0 $*"
+	sh $0 $*
+    done
+    exit
+}
+
+if [ -n "$DHCPIF" ]; then
+    CONFIG=@ETCCHILLI@/$DHCPIF/chilli.conf
+else
+    CONFIG=@SYSCONFDIR@/chilli.conf
+fi
+
+[ -f $CONFIG ] || {
+    echo "$CONFIG Not found"
+    exit 0
+}
 
 check_required
 
@@ -34,6 +57,7 @@ prog="chilli"
 case $1 in
     start)
         echo -n "Starting $prog: "
+
         /sbin/modprobe tun >/dev/null 2>&1
         echo 1 > /proc/sys/net/ipv4/ip_forward
 
@@ -46,22 +70,18 @@ case $1 in
 
 	writeconfig
         radiusconfig
-	
-        (crontab -l 2>&- | grep -v $0
-            test ${HS_ADMINTERVAL:-0} -gt 0 && echo "*/$HS_ADMINTERVAL * * * * $0 radconfig"
-            echo "*/10 * * * * $0 checkrunning"
-#           echo "*/2  * * * * $0 arping"
-        ) | crontab - 2>&-
+
+	test ${HS_ADMINTERVAL:-0} -gt 0 && {	
+            (crontab -l 2>&- | grep -v $0
+		echo "*/$HS_ADMINTERVAL * * * * $0 radconfig"
+		) | crontab - 2>&-
+	}
 	
 	ifconfig $HS_LANIF 0.0.0.0
-        $daemon @SBINDIR@/chilli &
+        $daemon @SBINDIR@/chilli -c $CONFIG &
         echo
 	;;
     
-    checkrunning)
-	[ -e $LKFILE -a ! -e $PIDFILE ] && $0 start
-	;;
-
     radconfig)
 	[ -e $MAIN_CONF ] || writeconfig
 	radiusconfig
@@ -82,14 +102,16 @@ case $1 in
 
 	crontab -l 2>&- | grep -v $0 | crontab -
 
-        [ -f @VARRUN@/chilli.pid ] && { 
-	    kill $(cat @VARRUN@/chilli.pid)
+        [ -f @VARRUN@/chilli.$HS_LANIF.pid ] && { 
+	    kill $(cat @VARRUN@/chilli.$HS_LANIF.pid)
 	    RETVAL=$
 	    [ $RETVAL = 0 ] && {
-		rm -f @VARRUN@/chilli.pid 2>/dev/null
+		rm -f @VARRUN@/chilli.$HS_LANIF.pid 2>/dev/null
 	    }
 	}
-	$killproc chilli
+
+	#$killproc chilli
+
         echo
 	;;
     
diff --git a/debian/coova-chilli.chilli.init b/debian/coova-chilli.chilli.init
--- a/debian/coova-chilli.chilli.init
+++ b/debian/coova-chilli.chilli.init
@@ -1,22 +1,9 @@
 #! /bin/sh
-#
-# skeleton	example file to build /etc/init.d/ scripts.
-#		This file should be used to construct scripts for /etc/init.d.
-#
-#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
-#		Modified for Debian GNU/Linux
-#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
-#
-# Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
-#
-# This file was automatically customized by dh-make on Thu,  1 Apr 2004 20:05:44 +0200
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/sbin/chilli
 NAME=chilli
 DESC=chilli
-CONFFILE=/etc/chilli.conf
-OPTS="--pidfile /var/run/$NAME.pid"
 
 START_CHILLI=0
 
@@ -30,89 +17,110 @@ if [ "$START_CHILLI" != "1" ] ; then
 fi
 
 test -f $DAEMON || exit 0
-test -f $CONFFILE || exit 0
-
 
 . /etc/chilli/functions
+
+MULTI=$(ls /etc/chilli/*/chilli.conf 2>/dev/null)
+[ -z "$DHCPIF" ] && [ -n "$MULTI" ] && {
+    for c in $MULTI; 
+    do
+	echo "Found configuration $c"
+	DHCPIF=$(basename $(echo $c|sed 's#/chilli.conf##'))
+	export DHCPIF
+	echo "Running DHCPIF=$DHCPIF $0 $*"
+	sh $0 $*
+    done
+    exit
+}
+
+if [ -n "$DHCPIF" ]; then
+    CONFIG=/etc/chilli/$DHCPIF/chilli.conf
+else
+    CONFIG=/etc/chilli.conf
+fi
+
+[ -f $CONFIG ] || {
+    echo "$CONFIG Not found"
+    exit 0
+}
 
 check_required
 
 RETVAL=0
 prog="chilli"
 
-
 case "$1" in
   start)
 	echo -n "Starting $DESC: "
-   /sbin/modprobe tun >/dev/null 2>&1
-   echo 1 > /proc/sys/net/ipv4/ip_forward
+	/sbin/modprobe tun >/dev/null 2>&1
+	echo 1 > /proc/sys/net/ipv4/ip_forward
+	
+	writeconfig
+	radiusconfig
+	
+	test ${HS_ADMINTERVAL:-0} -gt 0 && {	
+            (crontab -l 2>&- | grep -v $0
+		echo "*/$HS_ADMINTERVAL * * * * $0 radconfig"
+		) | crontab - 2>&-
+	}
 
-   writeconfig
-   radiusconfig
+	ifconfig $HS_LANIF 0.0.0.0
 
-   (crontab -l 2>&- | grep -v $0
-      test ${HS_ADMINTERVAL:-0} -gt 0 && echo "*/$HS_ADMINTERVAL * * * * $0 radconfig"
-      echo "*/10 * * * * $0 checkrunning"
-      #echo "*/2  * * * * $0 arping"
-   ) | crontab - 2>&-
-
-   ifconfig $HS_LANIF 0.0.0.0
-
-	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
-		--exec $DAEMON -- $OPTS
-   RETVAL=$?
+	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.$HS_LANIF.pid \
+		--exec $DAEMON -- -c $CONFIG
+	RETVAL=$?
 	echo "$NAME."
 	;;
-   
-   checkrunning)
-      check=`start-stop-daemon --start --exec $DAEMON --test`
-      if [ x"$check" != x"$DAEMON already running." ] ; then
-         $0 start
-      fi
-   ;;
-
-   radconfig)
-      [ -e $MAIN_CONF ] || writeconfig
-      radiusconfig
-   ;;
-
-   restart)
-      $0 stop
-      $0 start
-      RETVAL=$?
-   ;;
-
-  stop)
+    
+    checkrunning)
+	check=`start-stop-daemon --start --exec $DAEMON --test`
+	if [ x"$check" != x"$DAEMON already running." ] ; then
+            $0 start
+	fi
+	;;
+    
+    radconfig)
+	[ -e $MAIN_CONF ] || writeconfig
+	radiusconfig
+	;;
+    
+    restart)
+	$0 stop
+	$0 start
+	RETVAL=$?
+	;;
+    
+    stop)
 	echo -n "Stopping $DESC: "
-   
-   crontab -l 2>&- | grep -v $0 | crontab -
-
-
+	
+	crontab -l 2>&- | grep -v $0 | crontab -
+	
+	
 	start-stop-daemon --oknodo --stop --quiet --pidfile /var/run/$NAME.pid \
-		--exec $DAEMON
+	    --exec $DAEMON
 	echo "$NAME."
 	;;
-
-  reload)
-	 echo "Reloading $DESC."
-	 start-stop-daemon --stop --signal 1 --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON
-  ;;
-
-  condrestart)
-      check=`start-stop-daemon --start --exec $DAEMON --test`
-      if [ x"$check" != x"$DAEMON already running." ] ; then
-         $0 restart
+    
+    reload)
+	echo "Reloading $DESC."
+	start-stop-daemon --stop --signal 1 --quiet --pidfile \
+	    /var/run/$NAME.$HS_LANIF.pid --exec $DAEMON
+	;;
+    
+    condrestart)
+	check=`start-stop-daemon --start --exec $DAEMON --test`
+	if [ x"$check" != x"$DAEMON already running." ] ; then
+            $0 restart
             RETVAL=$?
-      fi
-   ;;
-
-   status)
-      status chilli
-      RETVAL=$?
-   ;;
-
-  *)
+	fi
+	;;
+    
+    status)
+	status chilli
+	RETVAL=$?
+	;;
+    
+    *)
 	N=/etc/init.d/$NAME
 	echo "Usage: $N {start|stop|restart|condrestart|status|reload|radconfig}" >&2
 	exit 1
